# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('relative_path', models.CharField(max_length=255, null=True, unique=True, verbose_name='File path')),
                ('content', models.TextField(blank=True, null=True)),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
            ],
            options={
                'verbose_name': 'File to edit',
                'verbose_name_plural': 'Files to edit',
            },
        ),
    ]
